#!/bin/bash

# Help

if [ $1 = "help" ]
then
  echo "cdir vg                              -Going into vagrant is"
  echo "cdir vg projectdir [subdirectory]    -Going to the docroot in the vagrant"
  echo "cdir p projectdir [subdirectory]     -Going to the docroot project"
  echo "cdir vgup                            -Start the machine vagrant and rsync // Do a sudo ls or something like that to set the password after execute script"
fi

# Going into vagrant
if [ $1 = "vg" ]
then
  #qdbus org.kde.yakuake /yakuake/sessions addSession
  # dbus org.kde.yakuake /yakuake/tabs setTabTitle "vg"
  qdbus org.kde.yakuake /yakuake/sessions runCommand "cd ~/vagrant/debian8"
  qdbus org.kde.yakuake /yakuake/sessions runCommand "ssh-add -k"
  qdbus org.kde.yakuake /yakuake/sessions runCommand "ssh -A vagrant@192.168.10.10"
  # cd ~/vagrant/debian8
  # ssh-add -k
  # ssh -A vagrant@192.168.10.10

  # Going to the docroot
  if [ "x$2" != "x$y" ]
  then
    qdbus org.kde.yakuake /yakuake/sessions runCommand "cd $2-local/codebase/docroot/$3 && clear"
  fi
fi

# Going main directory of project
if [ $1 = "p" ]
then
  # qdbus org.kde.yakuake /yakuake/sessions addSession
  # dbus org.kde.yakuake /yakuake/tabs setTabTitle "cb"
  qdbus org.kde.yakuake /yakuake/sessions runCommand "cd ~/vagrant/debian8/projects/codebases/$2-local/codebase/docroot/$3"
  # cd ~/vagrant/debian8/projects/codebases/$2-local/codebase/docroot/$3
fi

# Going main directory of project
if [ $1 = "vgup" ]
then
  # qdbus org.kde.yakuake /yakuake/sessions addSession
  # dbus org.kde.yakuake /yakuake/tabs setTabTitle "rsync"
  qdbus org.kde.yakuake /yakuake/sessions runCommand "cd vagrant/debian8 && vagrant up && vagrant rsync-auto"
  # cd ~/vagrant/debian8 && vagrant up && vagrant rsync-auto
fi
