#!/bin/bash
read -p 'Module (Example: "example_module"): ' module
read -p 'Short description (Example: "Fix error"): ' desc
read -p 'Issue id: ' issue
read -p 'comment number: ' cnumber
read -p 'Drupal version [8.x, 7.x] (Optional): ' version
# Version is optional.
desc=$(echo "${desc}" | sed 's/[[:space:]]/_/g' | tr '[:upper:]' '[:lower:]')
string="${module}-${desc}-${issue}-${cnumber}"

if [ ! -z "$version" ]
then
    string="${string}-${version}"
fi
diff=$(git diff)

echo $diff >> "${string}.patch"
