#!/bin/bash

# Setup yakuake
# vagrant vagrant tab.
qdbus org.kde.yakuake /yakuake/sessions org.kde.yakuake.addSession
qdbus org.kde.yakuake /yakuake/tabs setTabTitle 1 "vg"
qdbus org.kde.yakuake /yakuake/sessions runCommandInTerminal 1 "cd vagrant/debian8/ && clear"
qdbus org.kde.yakuake /yakuake/sessions runCommandInTerminal 1 "vagrant ssh"
qdbus org.kde.yakuake /yakuake/sessions runCommandInTerminal 1 "cd $1/codebase/docroot/"
