#!/bin/bash

# Setup yakuake
# Do a sudo ls or something like this to set the password after execute script

if [ "$1" = "help" ]
then
  echo "Do a sudo ls or something like that to set the password after execute script"
  echo " "
  echo "vgstart projectdir  -Prepare rsync tab, vagrant tab with docroot project, and codebase tab in docroot directory"
  echo "vgstart             -Same that previous but it does not change to the docroot directory"
else

  qdbus org.kde.yakuake /yakuake/tabs setTabTitle 0 "rsync"
  qdbus org.kde.yakuake /yakuake/sessions runCommandInTerminal 0 "cd ~/vagrant/debian8"
  qdbus org.kde.yakuake /yakuake/sessions runCommandInTerminal 0 "clear"
  qdbus org.kde.yakuake /yakuake/sessions runCommandInTerminal 0 "vagrant up && vagrant rsync-auto"

  # vagrant tab.
  qdbus org.kde.yakuake /yakuake/sessions org.kde.yakuake.addSession
  qdbus org.kde.yakuake /yakuake/tabs setTabTitle 1 "vg"
  qdbus org.kde.yakuake /yakuake/sessions runCommandInTerminal 1 "cd ~/vagrant/debian8/ && clear"
  qdbus org.kde.yakuake /yakuake/sessions runCommandInTerminal 1 "sleep 30"
  qdbus org.kde.yakuake /yakuake/sessions runCommand "ssh-add -k"
  qdbus org.kde.yakuake /yakuake/sessions runCommand "ssh -A vagrant@192.168.10.10"

  if [ "x$1" != "x$y" ]
  then
      qdbus org.kde.yakuake /yakuake/sessions runCommandInTerminal 1 "cd $1"
  fi

  # git codebase tab.
  qdbus org.kde.yakuake /yakuake/sessions org.kde.yakuake.addSession
  qdbus org.kde.yakuake /yakuake/tabs setTabTitle 2 "cb"
  if [ "x$1" != "x$y" ]
  then
    qdbus org.kde.yakuake /yakuake/sessions runCommandInTerminal 2 "cd ~/vagrant/debian8/projects/codebases/"
    qdbus org.kde.yakuake /yakuake/sessions runCommandInTerminal 2 "cd $1 && clear"
  fi
  qdbus org.kde.yakuake /yakuake/sessions runCommandInTerminal 2 "cd ~/vagrant/debian8/projects/codebases && clear"

fi
